use crate::Route;
use evertrace_domain::repository::RecoveryApplicationKind;
use evertrace_protocol::dto::{NegativeReviewDecision, ProposalHumanDecision};
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UiCommand {
    Language(crate::Language),
    Commands,
    Help,
    Filter,
    ClearFilter,
    FindNext,
    FindPrevious,
    Zoom,
    OpenResult,
    OpenResultAt(usize),
    CycleType,
    CycleScope,
    CycleState,
    SystemView(crate::state::SystemView),
    DetailView(crate::state::DetailView),
    Navigate(Route),
    Refresh,
    SelectNext,
    SelectPrevious,
    NextPage,
    FirstPage,
    Detail,
    OpenRelated,
    OpenFutureOperationShell,
    OpenProposalEditor,
    OpenConfigEditor,
    SubmitConfig,
    OpenSupportDeprecateEditor,
    PrepareProposal(ProposalHumanDecision),
    PrepareNegativeReview(NegativeReviewDecision),
    SelectCompetingPrevious,
    SelectCompetingNext,
    PrepareCompetingSelected,
    PrepareMarkNewAttempt,
    PrepareForgetObject,
    PrepareRepositoryPurge,
    PrepareRepositoryAccess(evertrace_protocol::dto::RepositoryAccessAction),
    PrepareCreateBackup,
    ToggleExportSelection,
    ExportSelection,
    PrepareCollectGarbage,
    PrepareVerifyBackup,
    ConfirmProposal,
    PrepareRecovery(RecoveryApplicationKind),
    ConfirmRecovery,
    CancelModal,
    Quit,
    None,
}

/// The three consumers (palette, help, buttons) share these current intents.
pub(crate) struct UiCommandSpec {
    pub command: UiCommand,
    pub name: &'static str,
    pub search_name: &'static str,
    pub reason: Option<&'static str>,
}
